### ISSUE TITLE
Enable pressure level extrapolation. 

### ISSUE THREAD

**Issue by bnb32** [NREL/sup3r#122]
https://github.com/NREL/sup3r/blob/24bfbad3da7c561bf70ded5b2af10f0bc35f0a7f/sup3r/utilities/utilities.py#L990 We are using np.interp here but this doesn't allow extrapolation below a provided height. Should replace with scipy.interpolate method.

**Comment by grantbuster** [comment]
I'll submit a PR when the branch is done: https://github.com/NREL/sup3r/commit/67b2898251544aa373b23b1b1ec363fbe377e0c1#diff-85433256d8944ef6a1e0f7dc33f4fe9e9267fd4c2c67bcda61af116658e1cd76R987

**Comment by grantbuster** [comment]
I think this was closed as part of https://github.com/NREL/sup3r/pull/124
