### ISSUE TITLE
log interpolation of windspeed

### ISSUE THREAD

**Issue by bnb32** [NREL/sup3r#154]
Implement log interpolation of windspeed in data handler extraction.

**Comment by grantbuster** [comment]
Good references at the links below. Had a really hard time getting the reading log fit to solve correctly. Note that if we use a power law extrapolation from a single surface wind (e.g., for some GCMs with limited data), we should extrapolate absolute windspeed and maintain direction. 

http://www.met.reading.ac.uk/~marc/it/wind/interp/log_prof/
https://en.wikipedia.org/wiki/Wind_profile_power_law

**Comment by bnb32** [comment]
> Good references at the links below. Had a really hard time getting the reading log fit to solve correctly. Note that if we use a power law extrapolation from a single surface wind (e.g., for some GCMs with limited data), we should extrapolate absolute windspeed and maintain direction.
> 
> http://www.met.reading.ac.uk/~marc/it/wind/interp/log_prof/ https://en.wikipedia.org/wiki/Wind_profile_power_law

Yeah I've been looking at this - https://en.wikipedia.org/wiki/Log_wind_profile. Seems the first link above has a sign mismatch with the wiki?

**Comment by grantbuster** [comment]
With the `-d` versus `+h` for the displacement height? Could be a mistake, although when using the algorithm from reading h was not constrained to be positive.

**Comment by bnb32** [comment]
> With the `-d` versus `+h` for the displacement height? Could be a mistake, although when using the algorithm from reading h was not constrained to be positive.

Yeah, and in some of my testing I got d to be negative when using -d anyway.
